### ISSUE TITLE
features.pkl处理脚本

### ISSUE THREAD

**Issue by yxk9810** [LchengC/iLIF#1]
hi，请问下生成features.pkl的数据处理脚本能否提供下? 适用自己的数据怎么处理成features的格式？

**Comment by LchengC** [comment]
hi，我写了一个从npy格式处理成features.pkl的代码供你参考，代码见[features_plk_process.zip](https://github.com/user-attachments/files/15830410/features_plk_process.zip)。
其中npy格式是我直接从原始数据集中初步处理得到的，全部采用的list嵌套的方式，你可以直接替换成你自己的数据，如果后续还有问题，欢迎随时询问

**Comment by yxk9810** [comment]
好的，感谢！

**Comment by LchengC** [comment]
您的邮件已收到，我会尽快处理，谢谢！

**Comment by yxk9810** [comment]
[process_data.zip](https://github.com/user-attachments/files/15845714/process_data.zip)
hi,抱歉再次打扰下，我的数据格式如下：
`{"new-ID": "10290", "doc": "成都市原市长助理门生涉嫌受贿案侦查终结，移送审查起诉_一号专案_澎湃新闻-ThePape。\n\n中新网成都1月5日电，5日，成都市人民检察院官方网站公布了近段时间成都市检察机关查处的4起职务犯罪案件信息。其中，原成都市市长助理、秘书长门生（副厅级）涉嫌受贿一案，由成都市人民检察院侦查终结，移送审查起诉。门生，男，汉族，1959年3月生，四川内江人。2009年门生因抗震救灾有功等原因，兼任成都市市长助理。2013年2月，门生转任成都市市长助理、市政府秘书长，并兼市政府办公厅党组书记，市委党校（行政学院）第一副校（院）长等职迄今。2015年06月10日，成都市纪委发布消息称，经成都市委同意，成都市纪委对成都市市长助理、市政府秘书长门生涉嫌严重违纪违法问题进行立案调查。门生是2014年8月以来，成都继陈争鸣、刘俊林及周鸿德之后落马的第4位市长助理。2015年9月17日，成都市人民检察院依法决定对成都市政府原市长助理、秘书长门生（副厅级）受贿立案侦查。2015年9月25日，经四川省人民检察院决定，依法对门生予以逮捕。此外，成都市检察院还公布了成都武侯区投资促进局副局长岳文婷、成都锦江区三圣街道办事处办公室原主任胡杨、成都市公积金管理中心原党委书记胡旭光的职务犯罪案件信息。", "events": [{"id": "10290_1", "event-information": {"trigger": [{"text": "立案侦查", "start": 422, "end": 426}], "event_type": "司法行为_立案调查"}}, {"id": "10290_2", "event-information": {"trigger": [{"text": "逮捕", "start": 457, "end": 459}], "event_type": "司法行为_拘捕"}}], "relations": [{"one_event_id": "10290_1", "other_event_id": "10290_2", "relation_type": "时序"}]}
`
事件关系只有2个类别，时序或者因果，代码我参考你之前给的做了处理，但是对于最后的pair部分有些疑问
1. pair 训练时候要把所有的pair 进行枚举？比如不在标注数据的relations里面的？
2. 然后第一次接触这个任务，这里面的类别或者relation 关系不知道我代码里面设置是否可以？或者我这个任务是否适合？如果有代码或者理解上的错误，还烦请帮忙指出下。 
多谢~

**Comment by YiQing-Songs** [comment]
> 您的邮件已收到，我会尽快处理，谢谢！

是否我能求一份您的数据格式，谢谢！

**Comment by LchengC** [comment]
您的邮件已收到，我会尽快处理，谢谢！

**Comment by LchengC** [comment]
> [process_data.zip](https://github.com/user-attachments/files/15845714/process_data.zip) hi,抱歉再次打扰下，我的数据格式如下： `{"new-ID": "10290", "doc": "成都市原市长助理门生涉嫌受贿案侦查终结，移送审查起诉_一号专案_澎湃新闻-ThePape。\n\n中新网成都1月5日电，5日，成都市人民检察院官方网站公布了近段时间成都市检察机关查处的4起职务犯罪案件信息。其中，原成都市市长助理、秘书长门生（副厅级）涉嫌受贿一案，由成都市人民检察院侦查终结，移送审查起诉。门生，男，汉族，1959年3月生，四川内江人。2009年门生因抗震救灾有功等原因，兼任成都市市长助理。2013年2月，门生转任成都市市长助理、市政府秘书长，并兼市政府办公厅党组书记，市委党校（行政学院）第一副校（院）长等职迄今。2015年06月10日，成都市纪委发布消息称，经成都市委同意，成都市纪委对成都市市长助理、市政府秘书长门生涉嫌严重违纪违法问题进行立案调查。门生是2014年8月以来，成都继陈争鸣、刘俊林及周鸿德之后落马的第4位市长助理。2015年9月17日，成都市人民检察院依法决定对成都市政府原市长助理、秘书长门生（副厅级）受贿立案侦查。2015年9月25日，经四川省人民检察院决定，依法对门生予以逮捕。此外，成都市检察院还公布了成都武侯区投资促进局副局长岳文婷、成都锦江区三圣街道办事处办公室原主任胡杨、成都市公积金管理中心原党委书记胡旭光的职务犯罪案件信息。", "events": [{"id": "10290_1", "event-information": {"trigger": [{"text": "立案侦查", "start": 422, "end": 426}], "event_type": "司法行为_立案调查"}}, {"id": "10290_2", "event-information": {"trigger": [{"text": "逮捕", "start": 457, "end": 459}], "event_type": "司法行为_拘捕"}}], "relations": [{"one_event_id": "10290_1", "other_event_id": "10290_2", "relation_type": "时序"}]} ` 事件关系只有2个类别，时序或者因果，代码我参考你之前给的做了处理，但是对于最后的pair部分有些疑问
> 
> 1. pair 训练时候要把所有的pair 进行枚举？比如不在标注数据的relations里面的？
> 2. 然后第一次接触这个任务，这里面的类别或者relation 关系不知道我代码里面设置是否可以？或者我这个任务是否适合？如果有代码或者理解上的错误，还烦请帮忙指出下。
>    多谢~

1. 训练的时候，其实看个人需要，因为测试和验证的时候，是枚举所有的事件对，所以我在训练过程也是将所有的事件对给枚举出来了，在relations里，也就是有因果的事件对作为正例，没有的作为负例。
2. 关于设置，由于你需要考虑时许和因果两种关系，而这两种关系恰好都有方向的概念在里面，所以你要做的就是保证你的数据集中能够体现这种方向的概念，或者说你能够从你处理后的数据集中争取的读取事件对之间的时许和因果关系即可。
至于说你现在的处理，我有一个小问题，因为你比较了start和end，这样是不是天然就固定了你只有一个方向的标签呢？

**Comment by LchengC** [comment]
> > 您的邮件已收到，我会尽快处理，谢谢！
> 
> 是否我能求一份您的数据格式，谢谢！

数据格式是指什么格式，是我处理从原始数据集到npy格式的数据集嘛

**Comment by LchengC** [comment]
> > 您的邮件已收到，我会尽快处理，谢谢！
> 
> 是否我能求一份您的数据格式，谢谢！

还是说我从最原始的xml文件中读取为npy格式的处理代码?

**Comment by YiQing-Songs** [comment]
> > > 您的邮件已收到，我会尽快处理，谢谢！
> > 
> > 
> > 是否我能求一份您的数据格式，谢谢！
> 
> 还是说我从最原始的xml文件中读取为npy格式的处理代码？

是的 最原始的xml文件处理成npy的代码 感谢！！

**Comment by LchengC** [comment]
您的邮件已收到，我会尽快处理，谢谢！

**Comment by LchengC** [comment]
[iLIF_数据集处理.zip](https://github.com/user-attachments/files/16833637/iLIF_.zip)
以上是我之前处理的处理数据集的版本，最近时间比较赶，所以没做太多的解释性和接口统一，如果遇到啥问题，你再联系我，里面附上了iLIF论文附录中预处理后的数据集。特别注意：这个文件处理出来的并不是这份iLIF用的最终形式，得结合我之前发给你那份转化为pkl的代码一起使用

**Comment by Z-lemon1** [comment]
> [process_data.zip](https://github.com/user-attachments/files/15845714/process_data.zip) hi,抱歉再次打扰下，我的数据格式如下： `{"new-ID": "10290", "doc": "成都市原市长助理门生涉嫌受贿案侦查终结，移送审查起诉_一号专案_澎湃新闻-ThePape。\n\n中新网成都1月5日电，5日，成都市人民检察院官方网站公布了近段时间成都市检察机关查处的4起职务犯罪案件信息。其中，原成都市市长助理、秘书长门生（副厅级）涉嫌受贿一案，由成都市人民检察院侦查终结，移送审查起诉。门生，男，汉族，1959年3月生，四川内江人。2009年门生因抗震救灾有功等原因，兼任成都市市长助理。2013年2月，门生转任成都市市长助理、市政府秘书长，并兼市政府办公厅党组书记，市委党校（行政学院）第一副校（院）长等职迄今。2015年06月10日，成都市纪委发布消息称，经成都市委同意，成都市纪委对成都市市长助理、市政府秘书长门生涉嫌严重违纪违法问题进行立案调查。门生是2014年8月以来，成都继陈争鸣、刘俊林及周鸿德之后落马的第4位市长助理。2015年9月17日，成都市人民检察院依法决定对成都市政府原市长助理、秘书长门生（副厅级）受贿立案侦查。2015年9月25日，经四川省人民检察院决定，依法对门生予以逮捕。此外，成都市检察院还公布了成都武侯区投资促进局副局长岳文婷、成都锦江区三圣街道办事处办公室原主任胡杨、成都市公积金管理中心原党委书记胡旭光的职务犯罪案件信息。", "events": [{"id": "10290_1", "event-information": {"trigger": [{"text": "立案侦查", "start": 422, "end": 426}], "event_type": "司法行为_立案调查"}}, {"id": "10290_2", "event-information": {"trigger": [{"text": "逮捕", "start": 457, "end": 459}], "event_type": "司法行为_拘捕"}}], "relations": [{"one_event_id": "10290_1", "other_event_id": "10290_2", "relation_type": "时序"}]} ` 事件关系只有2个类别，时序或者因果，代码我参考你之前给的做了处理，但是对于最后的pair部分有些疑问
> 
> 1. pair 训练时候要把所有的pair 进行枚举？比如不在标注数据的relations里面的？
> 2. 然后第一次接触这个任务，这里面的类别或者relation 关系不知道我代码里面设置是否可以？或者我这个任务是否适合？如果有代码或者理解上的错误，还烦请帮忙指出下。
>    多谢~

你好，我对你做的有关司法领域的事件关系研究很有兴趣，我也在进行相关研究，请问是否可以提供你的邮箱以方便交流？
