### ISSUE TITLE
关于MAVEN-ERE数据集

### ISSUE THREAD

**Issue by Z-lemon1** [LchengC/iLIF#10]
你好，请问可以提供您处理的，直接可用的MAVEN-ERE数据集和代码吗？十分感谢！

**Comment by LchengC** [comment]
您好，MAVEN-ERE其实是提供了直接上传测试集结果的网站。我是因为网站给出的评判结果无法满足ECI任务上更精细化的指标需求，所以遵循以前研究者在论文中阐述加上个人理解以及其他研究者讨论后，对MAVEN-ERE做了一些浅显处理。相较于ESC上已经成熟的处理方式不同，MAVEN-ERE上目前我也只是做了一些自认为的处理方式，还比较粗浅，同时MAVEN-ERE是其他团队的产物（并没有公开认可我这种处理方式），所以直接在github上直接公开我个人感觉没有那么恰当。但是如有研究需要可以邮件（liu_cheng@hust.edu.cn）联系我探讨交流该类问题。
