### ISSUE TITLE
数据格式疑问

### ISSUE THREAD

**Issue by yxk9810** [LchengC/iLIF#2]
请问下数据格式的t1_pos和t2_pos 是怎么得到的？

**Comment by LchengC** [comment]
> 请问下数据格式的t1_pos和t2_pos 是怎么得到的？

这个是根据原始数据集的标注结果来确定的，相当于label，其实我这么处理完全是为了方便写代码的时候读取label，所以才处理为了t1_pos和t2_pos。关于这个点，我个人的想法是只要你最后能方便的从你处理后的数据集中读取label足够了，并不是什么固定的格式
