### ISSUE TITLE
EventStoryLine xml处理成npy

### ISSUE THREAD

**Issue by WLucky** [LchengC/iLIF#3]
非常好的工作，我想深入研究下，可以提供下xml处理成npy的代码吗，谢谢!

**Comment by LchengC** [comment]
[iLIF_数据集处理.zip](https://github.com/user-attachments/files/16833637/iLIF_.zip)
以上是我之前处理的处理数据集的版本，最近时间比较赶，所以没做太多的解释性和接口统一，如果遇到啥问题，你再联系我，里面附上了iLIF论文附录中预处理后的数据集。特别注意：这个文件处理出来的并不是这份iLIF用的最终形式，得结合我之前发给你那份转化为pkl的代码一起使用

**Comment by LchengC** [comment]
> [iLIF_数据集处理.zip](https://github.com/user-attachments/files/16833637/iLIF_.zip) 以上是我之前处理的处理数据集的版本，最近时间比较赶，所以没做太多的解释性和接口统一，如果遇到啥问题，你再联系我，里面附上了iLIF论文附录中预处理后的数据集。特别注意：这个文件处理出来的并不是这份iLIF用的最终形式，得结合我之前发给你那份转化为pkl的代码一起使用

npy转pkl的代码在问题#1的回复里有给出

**Comment by Catworkdog** [comment]
> > [iLIF_数据集处理.zip](https://github.com/user-attachments/files/16833637/iLIF_.zip) 以上是我之前处理的处理数据集的版本，最近时间比较赶，所以没做太多的解释性和接口统一，如果遇到啥问题，你再联系我，里面附上了iLIF论文附录中预处理后的数据集。特别注意：这个文件处理出来的并不是这份iLIF用的最终形式，得结合我之前发给你那份转化为pkl的代码一起使用
> 
> npy转pkl的代码在问题#1的回复里有给出

![image](https://github.com/user-attachments/assets/31e0bfe2-46ec-4a2d-b518-116f47f8ead0)
process_event里面的代码删除Token会报错，我这里面

**Comment by WLucky** [comment]
> > [iLIF_数据集处理.zip](https://github.com/user-attachments/files/16833637/iLIF_.zip) 以上是我之前处理的处理数据集的版本，最近时间比较赶，所以没做太多的解释性和接口统一，如果遇到啥问题，你再联系我，里面附上了iLIF论文附录中预处理后的数据集。特别注意：这个文件处理出来的并不是这份iLIF用的最终形式，得结合我之前发给你那份转化为pkl的代码一起使用
> 
> npy转pkl的代码在问题#1的回复里有给出

非常感谢！

**Comment by Catworkdog** [comment]
> > > [iLIF_数据集处理.zip](https://github.com/user-attachments/files/16833637/iLIF_.zip) 以上是我之前处理的处理数据集的版本，最近时间比较赶，所以没做太多的解释性和接口统一，如果遇到啥问题，你再联系我，里面附上了iLIF论文附录中预处理后的数据集。特别注意：这个文件处理出来的并不是这份iLIF用的最终形式，得结合我之前发给你那份转化为pkl的代码一起使用
> > 
> > 
> > npy转pkl的代码在问题#1的回复里有给出
> 
> ![image](https://private-user-images.githubusercontent.com/80702484/363989329-31e0bfe2-46ec-4a2d-b518-116f47f8ead0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTI3MTUsIm5iZiI6MTcyNTU5MjQxNSwicGF0aCI6Ii84MDcwMjQ4NC8zNjM5ODkzMjktMzFlMGJmZTItNDZlYy00YTJkLWI1MTgtMTE2ZjQ3ZjhlYWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAzMTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjUwMmZhMGYyMTQ5NmYxZjZiMDg5YWZjMDY5ZjczMDE3ODk5NTZlMjEyYmQwMGQzYTVlMWI0NTkxMzFmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F6eeDi6_36x_Wn9d8eNKWS0Ee44v0l4qO7ug94h9KQY) process_event里面的代码删除Token会报错，我这里面

这个问题解决了，但是出现了一个新问题
![image](https://github.com/user-attachments/assets/89d57f4e-7ab4-400d-9e4c-54761f7f1302)
改完后的代码跑因果存在的效果只有f1只接近百分之40，pkl包的大小也小了1M左右

**Comment by LchengC** [comment]
> > > > [iLIF_数据集处理.zip](https://github.com/user-attachments/files/16833637/iLIF_.zip) 以上是我之前处理的处理数据集的版本，最近时间比较赶，所以没做太多的解释性和接口统一，如果遇到啥问题，你再联系我，里面附上了iLIF论文附录中预处理后的数据集。特别注意：这个文件处理出来的并不是这份iLIF用的最终形式，得结合我之前发给你那份转化为pkl的代码一起使用
> > > 
> > > 
> > > npy转pkl的代码在问题#1的回复里有给出
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/80702484/363989329-31e0bfe2-46ec-4a2d-b518-116f47f8ead0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTI3MTUsIm5iZiI6MTcyNTU5MjQxNSwicGF0aCI6Ii84MDcwMjQ4NC8zNjM5ODkzMjktMzFlMGJmZTItNDZlYy00YTJkLWI1MTgtMTE2ZjQ3ZjhlYWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAzMTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjUwMmZhMGYyMTQ5NmYxZjZiMDg5YWZjMDY5ZjczMDE3ODk5NTZlMjEyYmQwMGQzYTVlMWI0NTkxMzFmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F6eeDi6_36x_Wn9d8eNKWS0Ee44v0l4qO7ug94h9KQY) process_event里面的代码删除Token会报错，我这里面
> 
> 这个问题解决了，但是出现了一个新问题 ![image](https://private-user-images.githubusercontent.com/80702484/365021602-89d57f4e-7ab4-400d-9e4c-54761f7f1302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTEwNjAsIm5iZiI6MTcyNTg1MDc2MCwicGF0aCI6Ii84MDcwMjQ4NC8zNjUwMjE2MDItODlkNTdmNGUtN2FiNC00MDBkLTllNGMtNTQ3NjFmN2YxMzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAyNTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhOTA1NDliOWYyODMwNWEzMmVhNTc4NzgwODVlNmI1NmJhNDUxNTNiZGRlMDNlZWExMTk2NGUwYjhhZTAxMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QuFoWBxhK5p5f-kyphu8QlonK15VjMSEM1e8tCtuJlQ) 改完后的代码跑因果存在的效果只有f1只接近百分之40，pkl包的大小也小了1M左右

https://github.com/LchengC/iLIF/issues/4#issuecomment-2337007144
要不试试我的这版存在性数据集，因为iLIF的方向特性，获得存在性数据集的方式不能只改变label

**Comment by Catworkdog** [comment]
> > > > > [iLIF_数据集处理.zip](https://github.com/user-attachments/files/16833637/iLIF_.zip) 以上是我之前处理的处理数据集的版本，最近时间比较赶，所以没做太多的解释性和接口统一，如果遇到啥问题，你再联系我，里面附上了iLIF论文附录中预处理后的数据集。特别注意：这个文件处理出来的并不是这份iLIF用的最终形式，得结合我之前发给你那份转化为pkl的代码一起使用
> > > > 
> > > > 
> > > > npy转pkl的代码在问题#1的回复里有给出
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/80702484/363989329-31e0bfe2-46ec-4a2d-b518-116f47f8ead0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTI3MTUsIm5iZiI6MTcyNTU5MjQxNSwicGF0aCI6Ii84MDcwMjQ4NC8zNjM5ODkzMjktMzFlMGJmZTItNDZlYy00YTJkLWI1MTgtMTE2ZjQ3ZjhlYWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAzMTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjUwMmZhMGYyMTQ5NmYxZjZiMDg5YWZjMDY5ZjczMDE3ODk5NTZlMjEyYmQwMGQzYTVlMWI0NTkxMzFmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F6eeDi6_36x_Wn9d8eNKWS0Ee44v0l4qO7ug94h9KQY) process_event里面的代码删除Token会报错，我这里面
> > 
> > 
> > 这个问题解决了，但是出现了一个新问题 ![image](https://private-user-images.githubusercontent.com/80702484/365021602-89d57f4e-7ab4-400d-9e4c-54761f7f1302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTEwNjAsIm5iZiI6MTcyNTg1MDc2MCwicGF0aCI6Ii84MDcwMjQ4NC8zNjUwMjE2MDItODlkNTdmNGUtN2FiNC00MDBkLTllNGMtNTQ3NjFmN2YxMzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAyNTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhOTA1NDliOWYyODMwNWEzMmVhNTc4NzgwODVlNmI1NmJhNDUxNTNiZGRlMDNlZWExMTk2NGUwYjhhZTAxMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QuFoWBxhK5p5f-kyphu8QlonK15VjMSEM1e8tCtuJlQ) 改完后的代码跑因果存在的效果只有f1只接近百分之40，pkl包的大小也小了1M左右
> 
> [#4 (comment)](https://github.com/LchengC/iLIF/issues/4#issuecomment-2337007144) 要不试试我的这版存在性数据集，因为iLIF的方向特性，获得存在性数据集的方式不能只改变label

欧克欧克 非常感谢

**Comment by CAUCtoKUST** [comment]
> > > > > [iLIF_数据集处理.zip](https://github.com/user-attachments/files/16833637/iLIF_.zip) 以上是我之前处理的处理数据集的版本，最近时间比较赶，所以没做太多的解释性和接口统一，如果遇到啥问题，你再联系我，里面附上了iLIF论文附录中预处理后的数据集。特别注意：这个文件处理出来的并不是这份iLIF用的最终形式，得结合我之前发给你那份转化为pkl的代码一起使用
> > > > 
> > > > 
> > > > npy转pkl的代码在问题#1的回复里有给出
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/80702484/363989329-31e0bfe2-46ec-4a2d-b518-116f47f8ead0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTI3MTUsIm5iZiI6MTcyNTU5MjQxNSwicGF0aCI6Ii84MDcwMjQ4NC8zNjM5ODkzMjktMzFlMGJmZTItNDZlYy00YTJkLWI1MTgtMTE2ZjQ3ZjhlYWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAzMTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjUwMmZhMGYyMTQ5NmYxZjZiMDg5YWZjMDY5ZjczMDE3ODk5NTZlMjEyYmQwMGQzYTVlMWI0NTkxMzFmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F6eeDi6_36x_Wn9d8eNKWS0Ee44v0l4qO7ug94h9KQY) process_event里面的代码删除Token会报错，我这里面
> > 
> > 
> > 这个问题解决了，但是出现了一个新问题 ![image](https://private-user-images.githubusercontent.com/80702484/365021602-89d57f4e-7ab4-400d-9e4c-54761f7f1302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTEwNjAsIm5iZiI6MTcyNTg1MDc2MCwicGF0aCI6Ii84MDcwMjQ4NC8zNjUwMjE2MDItODlkNTdmNGUtN2FiNC00MDBkLTllNGMtNTQ3NjFmN2YxMzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAyNTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhOTA1NDliOWYyODMwNWEzMmVhNTc4NzgwODVlNmI1NmJhNDUxNTNiZGRlMDNlZWExMTk2NGUwYjhhZTAxMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QuFoWBxhK5p5f-kyphu8QlonK15VjMSEM1e8tCtuJlQ) 改完后的代码跑因果存在的效果只有f1只接近百分之40，pkl包的大小也小了1M左右
> 
> [#4 (comment)](https://github.com/LchengC/iLIF/issues/4#issuecomment-2337007144) 要不试试我的这版存在性数据集，因为iLIF的方向特性，获得存在性数据集的方式不能只改变label

作者您好，不好意思请问一下，如果想获得存在性的数据集，除了改变标签还需要做什么吗，我在尝试处理数据集，用你这边提供的数据集能基本复现论文中的效果，但是我自己处理的存在性数据集就效果很差。
