### ISSUE TITLE
关于不考虑因果方向代码的疑问

### ISSUE THREAD

**Issue by Z-lemon1** [LchengC/iLIF#4]
请问作者，在上传的代码中仅提供了考虑因果方向的训练和测试的代码，可以提供一下不考虑方向，只考虑存在的代码吗？
十分感谢！

**Comment by LchengC** [comment]
代码都是一份，主要变化是数据集，由于只考虑存在的数据集可以由考虑方向的数据集简易后得到，所以我就没贴。
具体做法：你可以把我给的考虑方向数据集的label由case、effect、none改为case、none或者effect、none。然后把参数--no_of_classes改为2，就可以得到只考虑存在的结果。如果遇到啥问题或者你需要我处理的只考虑存在的数据集，你可以再联系我，我可以提供只考虑存在的数据集。

**Comment by Z-lemon1** [comment]
我想我需要你提供一下处理好的，可以直接使用的，只考虑存在的数据，十分感谢！

**Comment by Catworkdog** [comment]
> 代码都是一份，主要变化是数据集，由于只考虑存在的数据集可以由考虑方向的数据集简易后得到，所以我就没贴。 具体做法：你可以把我给的考虑方向数据集的label由case、effect、none改为case、none或者effect、none。然后把参数--no_of_classes改为2，就可以得到只考虑存在的结果。如果遇到啥问题或者你需要我处理的只考虑存在的数据集，你可以再联系我，我可以提供只考虑存在的数据集。

数据集改成target为0,1格式的二分类之后，模型跑出来的跟有向的三分类f1值差不多

**Comment by Catworkdog** [comment]
> 我想我需要你提供一下处理好的，可以直接使用的，只考虑存在的数据，十分感谢！
[database2.zip](https://github.com/user-attachments/files/16914081/database2.zip)兄弟，你看看是不是我这数据集是不是处理错了

**Comment by Z-lemon1** [comment]
在实验中发现，作者提供的数据中，存在文档中事件个数与原数据的事件个数不匹配的现象，作者提供的事件个数较多。想问一下多出来的部分是怎么获得的？

**Comment by LchengC** [comment]
> 我想我需要你提供一下处理好的，可以直接使用的，只考虑存在的数据，十分感谢！
[existence dataset.zip](https://github.com/user-attachments/files/16973904/existence.dataset.zip)
这里是处理好的可以直接用的只考虑存在的数据

**Comment by LchengC** [comment]
> > 我想我需要你提供一下处理好的，可以直接使用的，只考虑存在的数据，十分感谢！
> > [database2.zip](https://github.com/user-attachments/files/16914081/database2.zip)兄弟，你看看是不是我这数据集是不是处理错了

兄弟，你好像只改变了label，没有对事件对之间的相对关系做相应的改变，我把我之前处理好的可以直接用的数据集也传上了，你要不试试我的这个

**Comment by Catworkdog** [comment]
> > > 我想我需要你提供一下处理好的，可以直接使用的，只考虑存在的数据，十分感谢！
> > > [database2.zip](https://github.com/user-attachments/files/16914081/database2.zip)兄弟，你看看是不是我这数据集是不是处理错了
> 
> 兄弟，你好像只改变了label，没有对事件对之间的相对关系做相应的改变，我把我之前处理好的可以直接用的数据集也传上了，你要不试试我的这个

嗯嗯 非常感谢

**Comment by LchengC** [comment]
> 我想我需要你提供一下处理好的，可以直接使用的，只考虑存在的数据，十分感谢！

兄弟，你是不是还问了：“在实验中发现，作者提供的数据中，存在文档中事件个数与原数据的事件个数不匹配的现象，作者提供的事件个数较多。想问一下多出来的部分是怎么获得的？”这个问题
我没找到你原始的提问，所以直接做一个简单的回复哈
我是直接在原数据集的基础上做的处理，数量上应该是不存在问题的。需要注意的一点是：我考虑了原始数据集论文中提到的所有10多种事件类型，有一些论文为了缓解正负比的问题，会认为删除其中的部分事件类型（有一些事件类型只涉及少量的因果关系，但是会引入大量的非因果关系）

**Comment by Z-lemon1** [comment]
非常感谢！我的疑问都得到了解决。

**Comment by Catworkdog** [comment]
> 代码都是一份，主要变化是数据集，由于只考虑存在的数据集可以由考虑方向的数据集简易后得到，所以我就没贴。 具体做法：你可以把我给的考虑方向数据集的label由case、effect、none改为case、none或者effect、none。然后把参数--no_of_classes改为2，就可以得到只考虑存在的结果。如果遇到啥问题或者你需要我处理的只考虑存在的数据集，你可以再联系我，我可以提供只考虑存在的数据集。

你好，我现在还有一个问题，代码是不是还得改一下别的啊，no_of_classes=2改了之后，我用你给的数据集跑了一下，效果不是很好，之后我把mlp输出改成为2的跑出来的效果也不是很好，是不是还有别的需要改一下？

**Comment by LchengC** [comment]
> > 代码都是一份，主要变化是数据集，由于只考虑存在的数据集可以由考虑方向的数据集简易后得到，所以我就没贴。 具体做法：你可以把我给的考虑方向数据集的label由case、effect、none改为case、none或者effect、none。然后把参数--no_of_classes改为2，就可以得到只考虑存在的结果。如果遇到啥问题或者你需要我处理的只考虑存在的数据集，你可以再联系我，我可以提供只考虑存在的数据集。
> 
> 你好，我现在还有一个问题，代码是不是还得改一下别的啊，no_of_classes=2改了之后，我用你给的数据集跑了一下，效果不是很好，之后我把mlp输出改成为2的跑出来的效果也不是很好，是不是还有别的需要改一下？

抱歉，上次手滑打包错数据集了，已经上传存在性数据集到https://github.com/LchengC/iLIF/tree/master/data/database/exist ，这版我简单验证了，结果应该是与我论文中所报告区别不大的，你试一下最新版，然后mlp的输出要改为2，最新版代码已经做了相应的更新

**Comment by Catworkdog** [comment]
> > > 代码都是一份，主要变化是数据集，由于只考虑存在的数据集可以由考虑方向的数据集简易后得到，所以我就没贴。 具体做法：你可以把我给的考虑方向数据集的label由case、effect、none改为case、none或者effect、none。然后把参数--no_of_classes改为2，就可以得到只考虑存在的结果。如果遇到啥问题或者你需要我处理的只考虑存在的数据集，你可以再联系我，我可以提供只考虑存在的数据集。
> > 
> > 
> > 你好，我现在还有一个问题，代码是不是还得改一下别的啊，no_of_classes=2改了之后，我用你给的数据集跑了一下，效果不是很好，之后我把mlp输出改成为2的跑出来的效果也不是很好，是不是还有别的需要改一下？
> 
> 抱歉，上次手滑打包错数据集了，已经上传存在性数据集到https://github.com/LchengC/iLIF/tree/master/data/database/exist ，这版我简单验证了，结果应该是与我论文中所报告区别不大的，你试一下最新版，然后mlp的输出要改为2，最新版代码已经做了相应的更新

嗯嗯 非常感谢你的分享

**Comment by Z-lemon1** [comment]
> > > 代码都是一份，主要变化是数据集，由于只考虑存在的数据集可以由考虑方向的数据集简易后得到，所以我就没贴。 具体做法：你可以把我给的考虑方向数据集的label由case、effect、none改为case、none或者effect、none。然后把参数--no_of_classes改为2，就可以得到只考虑存在的结果。如果遇到啥问题或者你需要我处理的只考虑存在的数据集，你可以再联系我，我可以提供只考虑存在的数据集。
> > 
> > 
> > 你好，我现在还有一个问题，代码是不是还得改一下别的啊，no_of_classes=2改了之后，我用你给的数据集跑了一下，效果不是很好，之后我把mlp输出改成为2的跑出来的效果也不是很好，是不是还有别的需要改一下？
> 
> 抱歉，上次手滑打包错数据集了，已经上传存在性数据集到https://github.com/LchengC/iLIF/tree/master/data/database/exist ，这版我简单验证了，结果应该是与我论文中所报告区别不大的，你试一下最新版，然后mlp的输出要改为2，最新版代码已经做了相应的更新

这个新版本的存在性数据集也不是很对劲，mlp的输出修改为2了，label里面依然是3个值，并且报错。我将labels中不是0的值都换为1再进行训练，结果和论文中区别很大

**Comment by LchengC** [comment]
> > > > 代码都是一份，主要变化是数据集，由于只考虑存在的数据集可以由考虑方向的数据集简易后得到，所以我就没贴。 具体做法：你可以把我给的考虑方向数据集的label由case、effect、none改为case、none或者effect、none。然后把参数--no_of_classes改为2，就可以得到只考虑存在的结果。如果遇到啥问题或者你需要我处理的只考虑存在的数据集，你可以再联系我，我可以提供只考虑存在的数据集。
> > > 
> > > 
> > > 你好，我现在还有一个问题，代码是不是还得改一下别的啊，no_of_classes=2改了之后，我用你给的数据集跑了一下，效果不是很好，之后我把mlp输出改成为2的跑出来的效果也不是很好，是不是还有别的需要改一下？
> > 
> > 
> > 抱歉，上次手滑打包错数据集了，已经上传存在性数据集到https://github.com/LchengC/iLIF/tree/master/data/database/exist ，这版我简单验证了，结果应该是与我论文中所报告区别不大的，你试一下最新版，然后mlp的输出要改为2，最新版代码已经做了相应的更新
> 
> 这个新版本的存在性数据集也不是很对劲，mlp的输出修改为2了，label里面依然是3个值，并且报错。我将labels中不是0的值都换为1再进行训练，结果和论文中区别很大

你确定用的我上传的最新版的数据集嘛，这个最新版的数据集我看了一下label只有0和1，不应该有3个值。另外最新版代码中mlp的输出已经修改为和no_of_classes参数绑定。然后存在性数据集的路径和方向性的路径不一样，相应的--cache_path参数需要手动修改为'./data/database/exist'，你修改没？

**Comment by Z-lemon1** [comment]
> > > > > 代码都是一份，主要变化是数据集，由于只考虑存在的数据集可以由考虑方向的数据集简易后得到，所以我就没贴。 具体做法：你可以把我给的考虑方向数据集的label由case、effect、none改为case、none或者effect、none。然后把参数--no_of_classes改为2，就可以得到只考虑存在的结果。如果遇到啥问题或者你需要我处理的只考虑存在的数据集，你可以再联系我，我可以提供只考虑存在的数据集。
> > > > 
> > > > 
> > > > 你好，我现在还有一个问题，代码是不是还得改一下别的啊，no_of_classes=2改了之后，我用你给的数据集跑了一下，效果不是很好，之后我把mlp输出改成为2的跑出来的效果也不是很好，是不是还有别的需要改一下？
> > > 
> > > 
> > > 抱歉，上次手滑打包错数据集了，已经上传存在性数据集到https://github.com/LchengC/iLIF/tree/master/data/database/exist ，这版我简单验证了，结果应该是与我论文中所报告区别不大的，你试一下最新版，然后mlp的输出要改为2，最新版代码已经做了相应的更新
> > 
> > 
> > 这个新版本的存在性数据集也不是很对劲，mlp的输出修改为2了，label里面依然是3个值，并且报错。我将labels中不是0的值都换为1再进行训练，结果和论文中区别很大
> 
> 你确定用的我上传的最新版的数据集嘛，这个最新版的数据集我看了一下label只有0和1，不应该有3个值。另外最新版代码中mlp的输出已经修改为和no_of_classes参数绑定。然后存在性数据集的路径和方向性的路径不一样，相应的--cache_path参数需要手动修改为'./data/database/exist'，你修改没？

那我再跑一下，看是不是我其他设置出了问题
