### ISSUE TITLE
运行环境问题

### ISSUE THREAD

**Issue by Catworkdog** [LchengC/iLIF#5]
这个给出的numpy版本是不是与python版本不兼容

**Comment by LchengC** [comment]
这份代码对numpy的版本要求没那么严格，但是我列出来的确实是我当时成功运行的环境，如果出现不兼容的问题，我建议安装numpy的时候不用指定版本

**Comment by Catworkdog** [comment]
> 这份代码对numpy的版本要求没那么严格，但是我列出来的确实是我当时成功运行的环境，如果出现不兼容的问题，我建议安装numpy的时候不用指定版本

非常感谢 环境确实没问题 应该是我本地Windows电脑conda环境的问题 我在服务器按着配置可以运行
