### ISSUE TITLE
这部分代码是不是写错了，应该是测试集的f1最大进行更新，而不是验证集，不然模型跑出来的数据跟你的实验数据对不上

### ISSUE THREAD

**Issue by Catworkdog** [LchengC/iLIF#6]
![image](https://github.com/user-attachments/assets/ab17bc34-f1fa-4ce5-873e-9ab60f254ac5)

**Comment by LchengC** [comment]
best_valid_f1是验证集的f1，best_valid_test_f1是测试集的f1，我是测试集和验证集的结果都会更新。更新逻辑是：取在验证集上效果最好的checkpoint的测试集结果作为最终结果

**Comment by Catworkdog** [comment]
> best_valid_f1是验证集的f1，best_valid_test_f1是测试集的f1，我是测试集和验证集的结果都会更新。更新逻辑是：取在验证集上效果最好的checkpoint的测试集结果作为最终结果

非常感谢你的回复，但是我还是有些疑问，正常不应该是取测试集最好的结果吗？我看最后更新时好像也是取测试集的结果

**Comment by LchengC** [comment]
> > best_valid_f1是验证集的f1，best_valid_test_f1是测试集的f1，我是测试集和验证集的结果都会更新。更新逻辑是：取在验证集上效果最好的checkpoint的测试集结果作为最终结果
> 
> 非常感谢你的回复，但是我还是有些疑问，正常不应该是取测试集最好的结果吗？我看最后更新时好像也是取测试集的结果

我的理解是：
1、如果不存在验证集才是直接取测试集最好的结果
2、如果存在验证集的时候，应该是取验证集最好的那个checkpoint模型在测试集上的结果，这种方式所得到的结果理论上来说会比第一种要低一些，但是能够使取的模型具备更强的泛化能力

**Comment by Catworkdog** [comment]
> > > best_valid_f1是验证集的f1，best_valid_test_f1是测试集的f1，我是测试集和验证集的结果都会更新。更新逻辑是：取在验证集上效果最好的checkpoint的测试集结果作为最终结果
> > 
> > 
> > 非常感谢你的回复，但是我还是有些疑问，正常不应该是取测试集最好的结果吗？我看最后更新时好像也是取测试集的结果
> 
> 我的理解是： 1、如果不存在验证集才是直接取测试集最好的结果 2、如果存在验证集的时候，应该是取验证集最好的那个checkpoint模型在测试集上的结果，这种方式所得到的结果理论上来说会比第一种要低一些，但是能够使取的模型具备更强的泛化能力

嗯嗯 非常感谢你的解答
