### ISSUE TITLE
请教您ESL数据集候选事件集合及MAVEN-ERE数据集处理的细节问题

### ISSUE THREAD

**Issue by lyj963** [LchengC/iLIF#9]
非常感谢您开源了您文章的代码，并提供了详细的数据处理支持，因为目前也在做事件因果关系带有方向和标签的分类，想向您请教和确认几个问题：
    1、ESL的数据集对应论文“The Event StoryLine Corpus: A New Benchmark for Causal and Temporal Relation Extraction”中提到了“However, we limited the annotation of PLOT LINKs to events which correspond to one of the following three classes: ACTION OCCURRENCE, ACTION PERCEPTION, ACTION STATE.” 应该是缩小了候选事件的范围。在您的代码中应该是对所有类型的n个事件处理，然后对n(n-1)个事件对进行有向分类是吗？
您觉得是应该限制事件类型还是对所有事件都处理比较好呢，因为开源的工作比较少不太清楚有没有一个公认的基准。而不同处理方式产生的负样本数量差别会很大，从模型实用性和不同数据集的适用性考虑肯定是不限制类型比较好，但是ESL数据集本身又有限制，不同处理方式对结果和训练过程影响很大。希望您能给出您的经验或者建议。
    2、请问您对MAVEN-ERE数据集上的实验能否提供处理后的数据集划分细节，或者处理代码，因为MAVEN-ERE没有测试集的ground truth，可能大家自己处理方式不同。希望您能提供您的划分方式便于我们follow您的工作。
    3、向您确认一下，您在MAVEN-ERE上的实验是不区分因果的标签（CAUSE/PRECONDITION），只进行方向的识别是吗？因为我目前的实验是在MAVEN-ERE提供的代码基础上做的，代码是同时区分方向和两类因果标签的，想向您确认一下您的方法是否也区分了因果的标签。
     4、我在运行您提供的features_plk_process/process.py时出现了很多Token indices sequence length is longer than the specified maximum sequence length for this model (750 > 512). Running this sequence through the model will result in indexing errors的错误，请问这个对运行您的代码正常得到结果有影响吗，或者有无合适的解决方法？
    希望您有时间的话能够回复，非常感谢！

**Comment by LchengC** [comment]
您好，已在您之前的邮件中做了回复，请查看邮件~

**Comment by lyj963** [comment]
> 您好，已在您之前的邮件中做了回复，请查看邮件~

已收到，非常感谢您的回复！

**Comment by Z-lemon1** [comment]
> 您好，已在您之前的邮件中做了回复，请查看邮件~

您好，我同样在MAVEN-ERE数据集上进行后续工作，希望可以得到您处理好的MAVEN-ERE存在性数据，或处理原始数据的代码。以便在同一基准下进行改进

**Comment by Z-lemon1** [comment]
> 非常感谢您开源了您文章的代码，并提供了详细的数据处理支持，因为目前也在做事件因果关系带有方向和标签的分类，想向您请教和确认几个问题： 1、ESL的数据集对应论文“The Event StoryLine Corpus: A New Benchmark for Causal and Temporal Relation Extraction”中提到了“However, we limited the annotation of PLOT LINKs to events which correspond to one of the following three classes: ACTION OCCURRENCE, ACTION PERCEPTION, ACTION STATE.” 应该是缩小了候选事件的范围。在您的代码中应该是对所有类型的n个事件处理，然后对n(n-1)个事件对进行有向分类是吗？ 您觉得是应该限制事件类型还是对所有事件都处理比较好呢，因为开源的工作比较少不太清楚有没有一个公认的基准。而不同处理方式产生的负样本数量差别会很大，从模型实用性和不同数据集的适用性考虑肯定是不限制类型比较好，但是ESL数据集本身又有限制，不同处理方式对结果和训练过程影响很大。希望您能给出您的经验或者建议。 2、请问您对MAVEN-ERE数据集上的实验能否提供处理后的数据集划分细节，或者处理代码，因为MAVEN-ERE没有测试集的ground truth，可能大家自己处理方式不同。希望您能提供您的划分方式便于我们follow您的工作。 3、向您确认一下，您在MAVEN-ERE上的实验是不区分因果的标签（CAUSE/PRECONDITION），只进行方向的识别是吗？因为我目前的实验是在MAVEN-ERE提供的代码基础上做的，代码是同时区分方向和两类因果标签的，想向您确认一下您的方法是否也区分了因果的标签。 4、我在运行您提供的features_plk_process/process.py时出现了很多Token indices sequence length is longer than the specified maximum sequence length for this model (750 > 512). Running this sequence through the model will result in indexing errors的错误，请问这个对运行您的代码正常得到结果有影响吗，或者有无合适的解决方法？ 希望您有时间的话能够回复，非常感谢！

请问您的问题是否得到了解决，我同样也需要进行MAVEN-ERE数据集上的工作，是否可以提供数据集内容？

**Comment by lyj963** [comment]
>
> 请问您的问题是否得到了解决，我同样也需要进行MAVEN-ERE数据集上的工作，是否可以提供数据集内容？
您好，作者之前发邮件回复了我的问题，并给出了maven-ere数据集的处理代码，但是考虑到作者可能在这个项目里再进行一些更新和修改，如果您想让作者直接在项目里更新这些内容，最好还是再联系一下作者征求一下他们的意见。
关于MAVEN-ERE作者的数据处理代码，您可以联系我的邮箱我先发给您。（liyingjie@iie.ac.cn）

**Comment by LchengC** [comment]
> > 您好，已在您之前的邮件中做了回复，请查看邮件~
> 
> 您好，我同样在MAVEN-ERE数据集上进行后续工作，希望可以得到您处理好的MAVEN-ERE存在性数据，或处理原始数据的代码。以便在同一基准下进行改进

MAVEN-ERE的处理方式还比较浅显，为避免对现有研究者的误导，还不适合在github上公开，所以还请您邮件联系我（liu_cheng@hust.edu.cn）讨论交流
